## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "alexjohnson.io"
theme = "hugo-story"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
googleAnalytics = "UA-44813077"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "alexjohnson.io"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/alexjohnson505"
  instagram = "https://instagram.com/alexjohnson505"
  linkedin = "https://www.linkedin.com/in/alexjohnson505"
  stackoverflow = "https://stackoverflow.com/users/1508105/alex-johnson"

assetDir = "/assets"